/**
 * @file types.ts
 * @description Global ambient type definitions, domain interfaces, workflow types, and global Google Apps Script declarations.
 */

/** Raw email header and content structure used for AI triage. */
interface EmailData {
  subject: string;
  sender: string;
  replyTo: string;
  to: string;
  cc: string;
  labels: string[];
  attachmentNames: string[];
  body: string;
}

/** Prediction output payload returned from email triage. */
interface AIPrediction {
  predictedProjectName?: string;
  predictedDiscipline?: string;
  error?: string;
  confidence?: number;
}

/** Discriminated union outcome for AI email triage execution. */
type AiPredictionResult =
  | { success: true; prediction: AIPrediction }
  | {
      success: false;
      error: {
        code: 'RATE_LIMITED' | 'MISSING_KEY' | 'API_FAILURE' | 'PARSE_FAILURE';
        userMessage: string;
      };
    };

/** Context containing valid contact and action options passed to deep AI submittal analysis. */
interface DeepAnalysisContext {
  contacts: Array<{ abbr: string; name: string }>;
  actions: Array<{ action: string }>;
}

/** Extracted metadata fields returned from multimodal submittal PDF analysis. */
interface DeepAnalysisPrediction {
  predictedSection?: string;
  predictedNumber?: string;
  predictedRevision?: string;
  predictedTitle?: string;
  predictedSpecTag?: string;
  predictedVendor?: string;
  predictedContactAbbr?: string;
  predictedAction?: string;
}

/** Discriminated union outcome for deep AI submittal analysis. */
type DeepAnalysisResult =
  | { success: true; analysis: DeepAnalysisPrediction }
  | {
      success: false;
      error: {
        code: "RATE_LIMITED" | "MISSING_KEY" | "API_FAILURE" | "PARSE_FAILURE" | "PDF_PROCESSING_ERROR";
        userMessage: string;
      };
    };

/** Service interface for email triage and submittal document deep AI analysis. */
interface AiAnalysisService {
  triageEmail?(emailData: EmailData, messageId?: string): Promise<AiPredictionResult>;
  analyzeSubmittal(
    sourceBlob: GoogleAppsScript.Base.Blob,
    emailText: string,
    contextObj: DeepAnalysisContext
  ): Promise<DeepAnalysisResult>;
}

/** Intermediate unvalidated dictionary of submittal fields extracted from email, filename, or card inputs. */
interface ParsedData {
  projectAbbr?: string;
  discipline?: string;
  specSection?: string;
  section?: string;
  submittalNum?: string;
  number?: string;
  revNum?: string;
  revision?: string;
  title?: string;
  action?: string;
  driveName?: string;
  driveId?: string;
  logFileId?: string;
  incomingRouting?: string;
  fileSource?: string;
  driveFileUrl?: string;
  contact?: string;
  targetKey?: string;
  driveFileId?: string;
  attachmentIndex?: number;
  pdfUrl?: string;
  fileName?: string;
  specTag?: string;
  relatedTag?: string;
  specTitle?: string;
  vendor?: string;
  date?: string;
  notes?: string;
}

/** Card UI state flash message object for error/warning banners and interactive prompts. */
interface FlashMessage {
  warning?: string;
  info?: string;
  error?: string;
  missingFields?: string[];
  promptAddTag?: boolean;
  promptAddVendor?: boolean;
  targetKey?: string;
  fileId?: string;
  url?: string;
  localPath?: string;
  title?: string;
  action?: string;
  incomingRouting?: string;
  projectAbbr?: string;
  directRowUrl?: string;
  failedColumns?: string[];
  emptyFallbacks?: string[];
  newFileName?: string;
  newDriveFileId?: string;
  debugPhase2?: string;
}

/** Drive item selection payload object. */
interface DriveItem {
  id: string;
  title: string;
  mimeType: string;
}

/** Event payload object passed to Google Workspace Add-on trigger handlers. */
interface GoogleAppsScriptEvent {
  gmail?: {
    messageId: string;
    accessToken: string;
  };
  drive?: {
    selectedItems: DriveItem[];
  };
  parameters?: Record<string, string>;
  formInputs?: Record<string, string[]>;
  formInput?: Record<string, string>;
}

/** Parameters passed to email notification template generators. */
interface EmailTemplateParams {
  projectAbbr?: string;
  targetKey?: string;
  title?: string;
  action?: string;
  url?: string;
  localPath?: string;
}

/** Result subject and HTML body strings generated by email notification templates. */
interface EmailTemplateResult {
  subject: string;
  body: string;
}

/** Shared Drive ID and name tuple. */
interface SharedDriveInfo {
  id: string;
  name: string;
}

/** Result container for internal Gemini HTTP fetch operations. */
interface GeminiFetchResult {
  success: boolean;
  response?: GoogleAppsScript.URL_Fetch.HTTPResponse;
  statusCode?: number | string;
  errorText?: string;
}

/** Action configuration entry from Settings sheet. */
interface ActionSetting {
  action: string;
  abbr: string;
  status: string;
}

/** Contact configuration entry from Settings sheet. */
interface ContactSetting {
  abbr: string;
  name: string;
}

/** Consolidated project settings parsed from spreadsheet Settings and Tag List tabs. */
interface LogSettings {
  contacts: ContactSetting[];
  actions: ActionSetting[];
  ffeTags: {
    tags: string[];
    vendors: string[];
    tagMap: Record<string, string>;
  };
  projectAbbr: string;
  logSheetId: number | null;
}

/** Context object for legacy process submission handlers. */
interface ProcessContext {
  e: GoogleAppsScriptEvent;
  form: Record<string, string>;
  p: Record<string, string>;
  discipline: string;
  logSheet: GoogleAppsScript.Spreadsheet.Sheet;
  headers: string[];
  getColIdx: (name: string) => number;
  selectedAction: { action: string; abbr: string; status: string };
  targetKey: string;
  groupKey: string;
  newFileName: string;
  boundedData: any[][];
  newChain: string;
  previousRowSheetIndex: number | null;
  sectionVal: string;
  numberVal: string;
  revisionVal: string;
  emptyFallbacks: string[];
}

/** Key-value dictionary of raw document string fields. */
type RawDocument = Record<string, string>;

/** Submittal details specific to Architectural discipline. */
interface ArchitectureDetails {
  discipline: "Architecture";
  section: string;
  number: string;
  title: string;
  revision: string;
}

/** Submittal details specific to FF&E discipline. */
interface FFEDetails {
  discipline: "FF&E";
  specTag: string;
  specTitle: string;
  vendor: string;
  revision: string;
  relatedTag?: string;
}

/** Strongly typed validated document domain model. */
interface ValidatedDocument {
  documentType: string;
  date: string;
  contact: string;
  action: string;
  notes?: string;
  incomingRouting?: string;
  disciplineDetails: ArchitectureDetails | FFEDetails;
}

/** Options and tag lists for submittal validation. */
interface ValidationContext {
  ffeTags?: {
    tags: string[];
    vendors: string[];
  };
  bypassTagValidation?: boolean;
  bypassVendorValidation?: boolean;
}

/** Discriminated union outcome for submittal validation. */
type ValidationResult =
  | { status: "success"; data: ValidatedDocument; warnings: string[] }
  | { status: "error"; errors: string[]; missingFields?: string[] }
  | { status: "interaction_required"; interactionType: "ADD_TAG" | "ADD_VENDOR"; message: string };

/** Function type for extracting group or sort keys from raw spreadsheet row arrays. */
type RowKeyFn = (row: any[], headers: string[]) => string;

/** Insertion position plan calculated for placing a new submittal into Google Sheets. */
interface RowInsertionPlan {
  targetRowIndex: number;
  insertBlankBefore: boolean;
  insertBlankAfter: boolean;
  finalRowIndex: number;
}

/** Options provided to Drive filing repository during file upload/movement. */
interface FilingOptions {
  targetFolderId: string;
  subfolderPath?: string[];
  newFileName?: string;
}

/** Result object returned from Drive filing operations. */
interface FilingResult {
  fileId: string;
  url: string;
  localPath: string;
  folderId: string;
}

/** Strategy pattern interface for discipline-specific submittal rules. */
interface DocumentLogStrategy<T = ValidatedDocument> {
  getGroupKey(doc: T): string;
  getSortKey(doc: T): string;
  getTargetKey(doc: T): string;
  getGroupKeyFromRow(row: any[], headers: string[]): string;
  getSortKeyFromRow(row: any[], headers: string[]): string;
  getTargetKeyFromRow(row: any[], headers: string[]): string;
  formatRowPayload(doc: T, options: { link: string; contactHistory: string; status: string }): Record<string, string>;
  getFileName(doc: T, contactHistory: string, actionAbbr: string): string;
  getFilingSubfolders?(doc: T): string[];
}

/** Options for appending submittals to log repository. */
interface AppendDocumentOptions {
  sheetName?: string;
  headers?: string[];
  link?: string;
  status?: string;
  actionAbbr?: string;
  updatePreviousStatus?: boolean;
  previousRowStatus?: string;
}

/** Result object returned after appending a document row to Google Sheets. */
interface AppendDocumentResult {
  targetKey: string;
  newFileName: string;
  contactHistory: string;
  rowIndex: number;
  failedColumns: string[];
  previousRowUpdated: boolean;
}

/** Repository interface managing Google Sheets log persistence, settings, and tag lists. */
interface LogRepository {
  getLogSettings(spreadsheetId: string, discipline: string): LogSettings;
  verifyAndFormatLogSheet(spreadsheetId: string): string[];
  addNewTagToTagList(spreadsheetId: string, newTag: string, newTitle: string): void;
  addNewVendorToTagList(spreadsheetId: string, newVendor: string): void;
  insertLogRow(
    spreadsheetId: string,
    headers: string[],
    rowData: any[],
    plan: RowInsertionPlan
  ): { rowIndex: number; failedColumns: string[] };
  appendDocument(
    spreadsheetId: string,
    document: ValidatedDocument,
    strategy: DocumentLogStrategy,
    options?: AppendDocumentOptions
  ): AppendDocumentResult;
}

declare class FormIntakeParser {
  static parse(formInput?: Record<string, string>): RawDocument;
}

declare class EmailIntakeParser {
  static parseProcoreEmail_(subject: string, body: string): Partial<ParsedData>;
  static parseFormaEmail_(subject: string, body: string): Partial<ParsedData>;
  static parseEmail(message?: GoogleAppsScript.Gmail.GmailMessage | null): ParsedData;
}

declare class DriveFilenameIntakeParser {
  static parse(filename?: string): RawDocument;
}

declare class DocumentPipeline {
  static parseFormIntake(formInput: Record<string, string>): RawDocument;
  static parseEmail(message?: GoogleAppsScript.Gmail.GmailMessage | null): ParsedData;
  static parseFilename(filename: string): RawDocument;
  static validate(rawDoc: RawDocument, context?: ValidationContext): ValidationResult;
  static processFormIntake(formInput: Record<string, string>, context?: ValidationContext): ValidationResult;
}

declare function validateDocument(rawDoc: RawDocument, context?: ValidationContext): ValidationResult;


// Global Ambient Function Declarations
declare function buildMainCard(e: GoogleAppsScriptEvent, initialData?: ParsedData | null, isTagChange?: boolean, flashMessage?: FlashMessage | null): GoogleAppsScript.Card_Service.Card;
declare function buildSuccessCard(fileId: string, newFileName: string, fileUrl: string, localPath: string, targetKey: string, itemTitle: string, discipline: string, section: string, specTag: string, targetFolderId: string, logFileId: string, isFiled?: boolean, projectAbbr?: string, action?: string, incomingRouting?: string, draftUrl?: string | null, directRowUrl?: string | null, failedColumns?: string[], emptyFallbacks?: string[]): GoogleAppsScript.Card_Service.Card;
declare function parseEmailData(message?: GoogleAppsScript.Gmail.GmailMessage | null): ParsedData;
declare function parseDriveFilename(filename: string): ParsedData;
declare function parseFormaEmail_(subject: string, body: string): Partial<ParsedData>;
declare function parseProcoreEmail_(subject: string, body: string): Partial<ParsedData>;
declare function fetchAndSaveFile(url: string, folderId: string): { success: boolean; error?: string; fileId?: string; fileName?: string };
declare function getBoundedData(logData: any[][]): any[][];
declare function getRowGroupKey(row: any[], discipline: string, headers: string[]): string;
declare function getRowSortKey(row: any[], discipline: string, headers: string[]): string;
declare function computeRowInsertionPlan(boundedData: any[][], headers: string[], rowData: any[], disciplineOrGroupKeyFn: string | RowKeyFn, sortKeyFn?: RowKeyFn): RowInsertionPlan;

/** PDF stamping options. */
interface StampOptions {
  newFileName: string;
  stampSubmittalNo: string;
  templateId: string;
}

/** Service interface for PDF stamping, page slicing, and form action extraction. */
interface PdfDocumentService {
  extractFormAction(fileId: string): Promise<string | null>;
  stampSubmittal(
    sourceBlob: GoogleAppsScript.Base.Blob,
    data: ParsedData,
    options: StampOptions
  ): Promise<GoogleAppsScript.Base.Blob>;
  slicePagesToBase64(
    sourceBlob: GoogleAppsScript.Base.Blob,
    maxPages: number
  ): Promise<string>;
}

/** Repository interface for Drive filing and local path resolution. */
interface DriveFilingRepository {
  getLocalPath(fileId: string): string;
  fileDocument(file: { fileId?: string; blob?: GoogleAppsScript.Base.Blob }, options: FilingOptions): FilingResult;
}

/** Provider interface for Shared Drive lists. */
interface DriveNameProvider {
  getAvailableDriveNames(): string[];
  getSharedDrives(): SharedDriveInfo[];
}

declare var defaultCardPresenter: CardPresenter;
declare function buildSuccessCard(...args: any[]): GoogleAppsScript.Card_Service.Card;
declare var defaultLogRepository: LogRepository;
declare var defaultDriveFilingRepository: DriveFilingRepository;
declare var defaultPdfDocumentService: PdfDocumentService;
declare var defaultAiAnalysisService: AiAnalysisService;
declare var defaultDriveNameProvider: DriveNameProvider;
declare function processSubmission(e: GoogleAppsScriptEvent): Promise<any>;

/** Policy detailing workflow actions (direction, stamping, subfolder rules). */
interface WorkflowActionPolicy {
  direction: "incoming" | "outgoing";
  useCsiSubfolder: boolean;
  stampPdf: boolean;
  updatePreviousStatus: boolean;
  previousRowStatus?: string;
}

/** Input object passed to DocumentWorkflowModule.executeWorkflow. */
interface DocumentWorkflowInput {
  validatedDoc: ValidatedDocument;
  logFileId: string;
  logSheetId?: number;
  targetFolderId: string;
  driveFileId?: string;
  fileSource?: string;
  messageId?: string;
  attachmentName?: string;
  driveFileUrl?: string;
  incomingRouting?: string;
  projectAbbr?: string;
  emptyFallbacks?: string[];
  selectedAction: { action: string; abbr: string; status: string };
  logRepository?: LogRepository;
  driveFilingRepository?: DriveFilingRepository;
  pdfDocumentService?: PdfDocumentService;
  strategy?: DocumentLogStrategy;
  driveApp?: any;
  gmailApp?: any;
  spreadsheetApp?: any;
}

/** Output result returned from DocumentWorkflowModule.executeWorkflow. */
interface DocumentWorkflowResult {
  fileId: string;
  targetKey: string;
  url: string;
  localPath: string;
  title: string;
  action: string;
  incomingRouting?: string;
  projectAbbr?: string;
  directRowUrl: string;
  failedColumns: string[];
  emptyFallbacks: string[];
  newFileName: string;
}

declare function getActionPolicy(action: string): WorkflowActionPolicy;
declare function getDocumentLogStrategy(doc: ValidatedDocument): DocumentLogStrategy;
declare function getDocumentTitle(doc: ValidatedDocument): string;

declare class DocumentWorkflowModule {
  static executeWorkflow(input: DocumentWorkflowInput): Promise<DocumentWorkflowResult>;
}

// Global declaration for pdf-lib evaluated at runtime
declare const PDFLib: any;


declare class ArchitectureSubmittalStrategy implements DocumentLogStrategy<ValidatedDocument> {
  getFilingSubfolders(doc: ValidatedDocument): string[];
  getGroupKey(doc: ValidatedDocument): string;
  getSortKey(doc: ValidatedDocument): string;
  getTargetKey(doc: ValidatedDocument): string;
  getGroupKeyFromRow(row: any[], headers: string[]): string;
  getSortKeyFromRow(row: any[], headers: string[]): string;
  getTargetKeyFromRow(row: any[], headers: string[]): string;
  formatRowPayload(doc: ValidatedDocument, options: { link: string; contactHistory: string; status: string }): Record<string, string>;
  getFileName(doc: ValidatedDocument, contactHistory: string, actionAbbr: string): string;
}

declare class FFESubmittalStrategy implements DocumentLogStrategy<ValidatedDocument> {
  getGroupKey(doc: ValidatedDocument): string;
  getSortKey(doc: ValidatedDocument): string;
  getTargetKey(doc: ValidatedDocument): string;
  getGroupKeyFromRow(row: any[], headers: string[]): string;
  getSortKeyFromRow(row: any[], headers: string[]): string;
  getTargetKeyFromRow(row: any[], headers: string[]): string;
  formatRowPayload(doc: ValidatedDocument, options: { link: string; contactHistory: string; status: string }): Record<string, string>;
  getFileName(doc: ValidatedDocument, contactHistory: string, actionAbbr: string): string;
}
